// flow-typed signature: 1b798012f9475480b79d5a932c5eee26
// flow-typed version: <<STUB>>/eslint-config-prettier_v^1.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-prettier/cli' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/rules/core' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/rules/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-prettier/cli.js' {
  declare module.exports: $Exports<'eslint-config-prettier/cli'>;
}
declare module 'eslint-config-prettier/index' {
  declare module.exports: $Exports<'eslint-config-prettier'>;
}
declare module 'eslint-config-prettier/index.js' {
  declare module.exports: $Exports<'eslint-config-prettier'>;
}
declare module 'eslint-config-prettier/rules/core.js' {
  declare module.exports: $Exports<'eslint-config-prettier/rules/core'>;
}
declare module 'eslint-config-prettier/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-prettier/rules/react'>;
}
